# Generated by Django 4.2.3 on 2023-08-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_rename_fecha_publicacion_posteo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='categorias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
